// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "url-shortener/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// URLShortener is an autogenerated mock type for the URLShortener type
type URLShortener struct {
	mock.Mock
}

// ShortenURL provides a mock function with given fields: ctx, originalURL
func (_m *URLShortener) ShortenURL(ctx context.Context, originalURL string) (*entities.URL, error) {
	ret := _m.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 *entities.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.URL, error)); ok {
		return rf(ctx, originalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.URL); ok {
		r0 = rf(ctx, originalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLShortener creates a new instance of URLShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLShortener {
	mock := &URLShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
