// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	operations "url-shortener/internal/application/contracts/url/operations"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetOriginal provides a mock function with given fields: ctx, request
func (_m *Service) GetOriginal(ctx context.Context, request operations.GetOriginalRequest) (operations.GetOriginalResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginal")
	}

	var r0 operations.GetOriginalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, operations.GetOriginalRequest) (operations.GetOriginalResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, operations.GetOriginalRequest) operations.GetOriginalResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(operations.GetOriginalResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, operations.GetOriginalRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenURL provides a mock function with given fields: ctx, request
func (_m *Service) ShortenURL(ctx context.Context, request operations.ShortenRequest) (operations.ShortenResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 operations.ShortenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, operations.ShortenRequest) (operations.ShortenResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, operations.ShortenRequest) operations.ShortenResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(operations.ShortenResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, operations.ShortenRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
