// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "url-shortener/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// URLProvider is an autogenerated mock type for the URLProvider type
type URLProvider struct {
	mock.Mock
}

// GetOriginal provides a mock function with given fields: ctx, shortURL
func (_m *URLProvider) GetOriginal(ctx context.Context, shortURL string) (*entities.URL, error) {
	ret := _m.Called(ctx, shortURL)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginal")
	}

	var r0 *entities.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.URL, error)); ok {
		return rf(ctx, shortURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.URL); ok {
		r0 = rf(ctx, shortURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLProvider creates a new instance of URLProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLProvider {
	mock := &URLProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
