// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "url-shortener/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// URLRepository is an autogenerated mock type for the URLRepository type
type URLRepository struct {
	mock.Mock
}

// GetByOriginal provides a mock function with given fields: ctx, original
func (_m *URLRepository) GetByOriginal(ctx context.Context, original string) (*entities.URL, error) {
	ret := _m.Called(ctx, original)

	if len(ret) == 0 {
		panic("no return value specified for GetByOriginal")
	}

	var r0 *entities.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.URL, error)); ok {
		return rf(ctx, original)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.URL); ok {
		r0 = rf(ctx, original)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, original)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByShort provides a mock function with given fields: ctx, short
func (_m *URLRepository) GetByShort(ctx context.Context, short string) (*entities.URL, error) {
	ret := _m.Called(ctx, short)

	if len(ret) == 0 {
		panic("no return value specified for GetByShort")
	}

	var r0 *entities.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.URL, error)); ok {
		return rf(ctx, short)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.URL); ok {
		r0 = rf(ctx, short)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, short)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, url
func (_m *URLRepository) Save(ctx context.Context, url *entities.URL) error {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.URL) error); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewURLRepository creates a new instance of URLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLRepository {
	mock := &URLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
