// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "url-shortener/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// URLSaver is an autogenerated mock type for the URLSaver type
type URLSaver struct {
	mock.Mock
}

// SaveOrGet provides a mock function with given fields: ctx, e
func (_m *URLSaver) SaveOrGet(ctx context.Context, e *entities.URL) (*entities.URL, error) {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrGet")
	}

	var r0 *entities.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.URL) (*entities.URL, error)); ok {
		return rf(ctx, e)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.URL) *entities.URL); ok {
		r0 = rf(ctx, e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.URL) error); ok {
		r1 = rf(ctx, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLSaver creates a new instance of URLSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLSaver {
	mock := &URLSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
